spring:
  application:
    name: notification-service
  main:
    web-application-type: none # Service này chạy ngầm (worker), không cần web server (Tomcat)

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# ---------- Actuator (Health Check) ----------
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# ---------- Logging ----------
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [traceId=%X{traceId},spanId=%X{spanId}] - %msg%n"
  level:
    com.iuhconnect: INFO
